/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EsenciaRouteImport } from './routes/esencia'
import { Route as DestacadoRouteImport } from './routes/destacado'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'

const EsenciaRoute = EsenciaRouteImport.update({
  id: '/esencia',
  path: '/esencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DestacadoRoute = DestacadoRouteImport.update({
  id: '/destacado',
  path: '/destacado',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/destacado': typeof DestacadoRoute
  '/esencia': typeof EsenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/destacado': typeof DestacadoRoute
  '/esencia': typeof EsenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/destacado': typeof DestacadoRoute
  '/esencia': typeof EsenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo' | '/destacado' | '/esencia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo' | '/destacado' | '/esencia'
  id: '__root__' | '/' | '/catalogo' | '/destacado' | '/esencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  DestacadoRoute: typeof DestacadoRoute
  EsenciaRoute: typeof EsenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/esencia': {
      id: '/esencia'
      path: '/esencia'
      fullPath: '/esencia'
      preLoaderRoute: typeof EsenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destacado': {
      id: '/destacado'
      path: '/destacado'
      fullPath: '/destacado'
      preLoaderRoute: typeof DestacadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  DestacadoRoute: DestacadoRoute,
  EsenciaRoute: EsenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
